name: VPS Overview
on:
  workflow_dispatch:

jobs:
  overview:
    runs-on: ubuntu-latest
    steps:
      - name: Collect system overview via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "### System und Kernel:"
            uname -a
            echo "### Distribution:"
            (lsb_release -a 2>/dev/null) || cat /etc/os-release
            echo "### Uptime und Speicher:"
            uptime
            free -h
            echo "### Festplattenbelegung:"
            df -h
            echo "### Laufende Dienste:"
            systemctl list-units --type=service --state=running --no-pager
            echo "### Top-Prozesse:"
            top -b -n1 | head -n 15
            echo "### Anzahl installierter Pakete:"
            dpkg -l | wc -l || true
