name: VPS Overview

on:
  workflow_dispatch:

jobs:
  overview:
    name: Systemdiagnose (VPS Overview)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Collect system information
        run: |
          echo "===== HOST INFORMATION =====" > system-report.log
          hostnamectl >> system-report.log || true
          echo "" >> system-report.log

          echo "===== OS RELEASE =====" >> system-report.log
          lsb_release -a 2>/dev/null || cat /etc/os-release >> system-report.log
          echo "" >> system-report.log

          echo "===== KERNEL =====" >> system-report.log
          uname -a >> system-report.log
          echo "" >> system-report.log

          echo "===== RUNNING SERVICES =====" >> system-report.log
          systemctl list-units --type=service --state=running | head -n 40 >> system-report.log
          echo "" >> system-report.log

          echo "===== NETWORK PORTS =====" >> system-report.log
          ss -tuln | grep -E "80|443|33073|51820" >> system-report.log || echo "Keine relevanten Ports gefunden" >> system-report.log
          echo "" >> system-report.log

          echo "===== INSTALLED PACKAGES =====" >> system-report.log
          dpkg --get-selections | grep -E "netbird|caddy|nginx|postgres|mysql|docker" >> system-report.log || echo "Keine dieser Pakete gefunden" >> system-report.log
          echo "" >> system-report.log

          echo "===== RESOURCE USAGE =====" >> system-report.log
          df -h >> system-report.log
          free -m >> system-report.log
          echo "" >> system-report.log

      - name: Upload system report
        uses: actions/upload-artifact@v4
        with:
          name: vps-system-report
          path: system-report.log
